name: stafftaskspace
services:
  app:
    env_file: app.env
    image: stafftaskspace:latest
    networks:
      - backend-net
    ports:
      - ${PORTS}
    depends_on:
      db:
        condition: service_healthy
        restart: true
  db:
    env_file: db.env
    image: postgres:17.7-alpine
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DB}
    volumes:
     - dbdata:/var/lib/postgresql/data
    networks:
      - backend-net
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      timeout: 5s
      retries: 5

networks:
  backend-net:

volumes:
  dbdata: